// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2lGuAUoYNkbMlOrOPiy7UASwUaVkeyXE',
    appId: '1:163122390742:android:1f4898f34a8d7b72630b77',
    messagingSenderId: '163122390742',
    projectId: 'sltb-survey-app',
    storageBucket: 'sltb-survey-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWcQxz_VhjmWEgkykMbNAnLeNWlT9f31E',
    appId: '1:163122390742:ios:aa67a15be10d2964630b77',
    messagingSenderId: '163122390742',
    projectId: 'sltb-survey-app',
    storageBucket: 'sltb-survey-app.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtCizPz8pJzhF9MEyd7GxemvnyazEAGfw',
    appId: '1:163122390742:web:aa3d2fadcaac25f1630b77',
    messagingSenderId: '163122390742',
    projectId: 'sltb-survey-app',
    authDomain: 'sltb-survey-app.firebaseapp.com',
    storageBucket: 'sltb-survey-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtCizPz8pJzhF9MEyd7GxemvnyazEAGfw',
    appId: '1:163122390742:web:99329f8aa63f6df1630b77',
    messagingSenderId: '163122390742',
    projectId: 'sltb-survey-app',
    authDomain: 'sltb-survey-app.firebaseapp.com',
    storageBucket: 'sltb-survey-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWcQxz_VhjmWEgkykMbNAnLeNWlT9f31E',
    appId: '1:163122390742:ios:aa67a15be10d2964630b77',
    messagingSenderId: '163122390742',
    projectId: 'sltb-survey-app',
    storageBucket: 'sltb-survey-app.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

}